### PR TITLE
Fix/calendar datepicker default

### LINKED ISSUE #51: Ensure `Calendar.shinyInput` and `DatePicker.shinyInput` with `value = NULL` behave intuitively
When `value = NULL` is passed to `Calendar.shinyInput` or `DatePicker.shinyInput`, they use the current date in the browser, but start with a `NULL` value when accessed in Shiny (`input$`). In contrast, e.g. `shiny::dateInput()` uses current day if given `value = NULL`.

### LINKED ISSUE #106: support argument `placeholder` for `DatePicker.shinyInput()`
Referring to Microsoft FluentUI documentation: https://developer.microsoft.com/en-us/fluentui#/controls/web/datepicker

image

Currently, `DatePicker.shinyInput()` defaults to a value of current date if not specified. I am not able to use the `placeholder` argument to fill with text. Always defaults to current date of system.

I would like the DatePicker to have `null` value with text string "Select a date..."

### PR DESCRIPTION
**Pull request by jonekeat**
Fixes #51, 
Fixes #106 

Changes proposed in this pull request:
- use `shiny.react::JS("new Date()")` as new default values for `Calendar.shinyInput()` & `DatePicker.shinyInput()`. This is to make clear that the default is using **current date and time**
- change falsy values (eg. `NULL`, `NA`, `NaN`, `""`, ...etc) of `value` to `undefined` in *\js\src\inputs.jsx*. This is to ease normal R users work (or just me?) to replicate the [Official Doc behavior](https://developer.microsoft.com/en-us/fluentui#/controls/web/datepicker)
- (internal changes) updated `install.sh`, to prevent it from closing after run

I am grateful to all authors & contributors for this amazing package, and always wanted to contribute parts of it. However, I am very new to Javascripts or React, so please let me know if I did something wrong

# Screenshots
Below is the reproducible example for new behavior (at first loaded)
``` r
library(shiny)
library(shiny.fluent)

# missing `value`, default to `shiny.react::JS("new Date()")` which is current date
# consistent with `shiny::dateInput()` default
# but placeholder not shown
shinyApp(
  ui = div(
    Calendar.shinyInput("calendar"),
    DatePicker.shinyInput("date", placeholder = "I am placeholder!"),
    textOutput("calendarValue"),
    textOutput("dateValue")
  ),
  server = function(input, output) {
    output$calendarValue <- renderText({
      sprintf("Calendar Value: %s", input$calendar)
    })
    output$dateValue <- renderText({
      sprintf("DatePicker Value: %s", input$date)
    })
  }
)
```
image

```r
# `value` must specify `NULL`
# consistent with Microsoft Fluent UI default (`undefined`?)
# placeholder finally shown 
shinyApp(
  ui = div(
    Calendar.shinyInput("calendar", value = NULL),
    DatePicker.shinyInput("date", value = NULL, placeholder = "I am placeholder!"),
    textOutput("calendarValue"),
    textOutput("dateValue")
  ),
  server = function(input, output) {
    output$calendarValue <- renderText({
      sprintf("Calendar Value: %s", input$calendar)
    })
    output$dateValue <- renderText({
      sprintf("DatePicker Value: %s", input$date)
    })
  }
)
```
image

# PR checklist

- [x] Unit tests added
- [x] Documentation updated

### CODE REVIEW

File: R/inputs.R [hunk 1]
```diff
@@ -112,7 +112,7 @@ updateComboBox.shinyInput <- shiny.react::updateReactInput
 
 #' @rdname DatePicker
 #' @export
-DatePicker.shinyInput <- input("DatePicker", NULL)
+DatePicker.shinyInput <- input("DatePicker", shiny.react::JS("new Date()"))
```
Comment (jakubsob) [inline R/inputs.R:115]: Let's use R function to achieve the same effect:
```suggestion
DatePicker.shinyInput <- input("DatePicker", Sys.Date())
```

File: install.sh [hunk 2]
```diff
@@ -12,3 +12,7 @@ Rscript -e 'devtools::document()'
 
 # Install the package
 Rscript -e 'devtools::install()'
+
+# prevent terminal close
+printf "\n"
+read -p "Press enter to continue..."
```
Comment (jakubsob) [inline install.sh:18]: I'm not sure about this feature, could you elaborate why you've added it?
```suggestion
```

**Comment by jakubsob** [comment]
Thanks @jonekeat, really nice work!

Do you think you could also add e2e tests to cover this new behaviour?

I suggested to use R for setting default values of those components. I also have doubts about changes done to install script. 

When it comes to documentation, please just add those examples you've provided to example apps for each component, i.e. add 
```r
shinyApp(
  ui = fluentPage(
    DatePicker.shinyInput("date", value = NULL, placeholder = "I am placeholder!"),
    textOutput("dateValue")
  ),
  server = function(input, output) {
    output$dateValue <- renderText({
      sprintf("DatePicker Value: %s", input$date)
    })
  }
)
```
to [Date Picker example app](https://github.com/Appsilon/shiny.fluent/blob/master/inst/examples/DatePicker.R), it will be automatically added to examples section in documentation when it's rebuilt.

**Review by jakubsob — CHANGES_REQUESTED** [review]

File: install.sh (hunk 2 above)
Comment (jonekeat) [reply install.sh:18]: This few lines is to prevent shell terminal exits immediately, even encounter errors. I think when I first run the shell, it just exited silently, and after awhile of trial & errors, just figure out i dont have yarn installed 🤣 . 
I think is better for developers to see the shell messages, is just my opinion, I can remove these lines if this is a bad idea

File: R/inputs.R [hunk 3]
```diff
@@ -72,7 +72,7 @@ input <- function(name, defaultValue) {
 
 #' @rdname Calendar
 #' @export
-Calendar.shinyInput <- input("Calendar", NULL)
+Calendar.shinyInput <- input("Calendar", shiny.react::JS("new Date()"))
```
[the remark this answers is not in the document]
Comment (jonekeat) [reply R/inputs.R:75]: When I switch to `Sys.Date`, the default will return `2022-02-25` which is not consistent with Fluent UI date format, eg `2022-02-25T00:56:21.086Z`
If insist, we can use `strftime(Sys.time(), tz = "UTC", format = "%Y-%m-%dT%H:%M:%OS3Z")` in R to (roughly) match JS date format, but I am not sure whether there are discrepancies, see https://stackoverflow.com/questions/51597248/r-date-time-yyyy-mm-ddthhmmss-sssz-formate

**Comment by jonekeat** [comment]
@jakubsob Thanks for the comments, as for e2e-test, can you give me some hints on how to progress? I am not really sure how it works

File: R/inputs.R [hunk 4]
```diff
@@ -72,7 +72,16 @@ input <- function(name, defaultValue) {
...
+Calendar.shinyInput <- function(inputId, ..., value = shiny.react::JS("new Date()")) {
+  if (is.null(value)) {
+    value <- shiny.react::JS("new Date()")
+  }
+  shiny.react::reactElement(
+    module = "@/shiny.fluent", name = "Calendar",
+    props = shiny.react::asProps(inputId = inputId, ..., value = value),
+    deps = shinyFluentDependency()
+  )
+}
```
Comment (jonekeat) [inline R/inputs.R:84]: I am not sure how to set value to system date when `value = NULL`, here is the easiest workaround I could think of

**Comment by jonekeat** [comment]
@jakubsob I have added e2e-test for Calendar & DatePicker, but since when expected to return system date, I think cannot compare exactly up to millisecond else test will always failed, so I just compare the year, month & date of current date

Below is the screenshot of test result
image

File: NEWS.md [hunk 5]
```diff
@@ -1,3 +1,8 @@
+# shiny.fluent 0.2.1
+
+* Ensure `Calendar.shinyInput` and `DatePicker.shinyInput` with `value = NULL` to behave
+  consistently with the official behavior. [#118](https://github.com/Appsilon/shiny.fluent/pull/118)
+
```
Comment (jonekeat) [inline NEWS.md:5]: @jakubsob since this PR will introduce breaking changes (return values of `Calendar` & `DatePicker` changed), is it better we increment minor version eg. 0.3.0?

Comment (jakubsob) [reply NEWS.md:5]: The package is still not on CRAN and the version is `0.[...]` so breaking changes are expected to occur. Let's increment the version to 0.2.2

**Review by jakubsob — CHANGES_REQUESTED** [review]
Looks really nice! Let's just change a few things and we're ready to go :)

File: R/inputs.R (hunk 4 above)
Comment (jakubsob) [reply R/inputs.R:84]: I think it's fine for now

File: install.sh (hunk 2 above)
[the remark this answers is not in the document]
Comment (jonekeat) [reply install.sh:18]: @jakubsob I am not very sure where to put trailing new line, do you mean put after "Press enter to continue..."?

[the remark this answers is not in the document]
Comment (jakubsob) [reply install.sh:18]: Yes, exactly. The diff shows that it's missing: 
image

[the remark this answers is not in the document]
Comment (jonekeat) [reply install.sh]: Done
